# Generated by Django 3.0.8 on 2020-08-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profiles',
            new_name='user_profile',
        ),
    ]
